---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data
```{r, warning=FALSE, message=FALSE}
require(data.table)

dataFrame <- read.csv(unz("activity.zip", "activity.csv"))
data <- as.data.table(dataFrame)
```

### What is mean total number of steps taken per day?
```{r}
hist(data[,.(sumSteps = sum(steps)), by=date]$sumSteps, xlab="Total steps per day", main = "Histogram of total steps per day")
```
.  
###Mean total number of steps per day
```{r}
data[, .(sum=sum(steps)), by=date][,mean(sum, na.rm=TRUE)]
```
  
### Median total number of steps per day
```{r}
data[, .(sum=sum(steps)), by=date][,median(sum, na.rm=TRUE)]
```

## What is the average daily activity pattern?
```{r}
meanStepsPerInterval<-data[,.(meanSteps = mean(steps, na.rm=TRUE)), by=interval]
plot(meanStepsPerInterval$meanSteps~meanStepsPerInterval$interval, type = "l", xlab="Time Interval(hhmm)", ylab="mean steps", main="Mean Steps per time of day")
```
### Maximum activity in interval
```{r}
interval<-meanStepsPerInterval[which.max(meanSteps),interval]
paste(interval%/%100, interval%%100, sep=":")
```
## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
